[package]
name = "mongodb_sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.5.0"
chrono = "0.4.23"
dotenv = "0.15.0"
mongodb = "2.3.1"
serde = "1.0.152"
tokio = "1.25.0"
